### ISSUE TITLE
Improve user manual

### ISSUE THREAD

**Issue by tmfrnz** [impactoss/impactoss-client#460]
- [x] Better instructions and screenshots for CSV import feature, see https://github.com/impactoss/impactoss-user-manual/issues/6
- [x] Better instructions on viewing draft recommendations, see https://github.com/impactoss/impactoss-user-manual/issues/7
- [x] Instructions on reference numbers, see https://github.com/impactoss/impactoss-user-manual/issues/8
- [x] Better instructions on list view modes (expand/collapse), see https://github.com/impactoss/impactoss-user-manual/issues/9
- [x] Clarify new categories vs new category groupings, see https://github.com/impactoss/impactoss-user-manual/issues/10
- [ ] Add more screenshots to user guide in general, see https://github.com/impactoss/impactoss-user-manual/issues/11

**Comment by tmfrnz** [comment]
Re CSV import:

> There should be clearer instructions in the User Manual on the uploading function with illustrations or screenshots on how to fill it in (the instructions in the manual are very brief).

**Comment by tmfrnz** [comment]
Re draft recommendations

> We also encountered some difficulties uploading single items or drafts. After saving a draft recommendation, we could not find the draft on the website, except by searching all recommendations using the search tool. It might be useful to have a page for all draft recommendations.

Also see #456

**Comment by tmfrnz** [comment]
Re reference numbers

> The requirement for a reference number may throw some users off, as they might not remember what the reference number assigned to a particular issue was.

**Comment by tmfrnz** [comment]
Re view modes

> Under the “Implementation Plan” section, users can click on the progress indicators or progress updates symbols which expand and provide more information on the indicator. However clicking on an indicator/progress update expands all indicators and progress updates for all items in the list. There’s also no way to close the expanded items without exiting the “Implementation plan section”.

**Comment by tmfrnz** [comment]
Re categories vs taxonomies

> We cannot add new filter categories to include SDGs or anything else. (At present, the pre-loaded filter categories are: recommendation clusters, themes, human rights, affected persons groups, recommending mechanisms, reporting cycles.) As per the User Manual, the addition of new categories is a feature that should be available but is not working in practice

**Comment by tmfrnz** [comment]
General

> The User Manual comes across as complicated.  It is best if the key functions of the data management tool can be explained more simply.  We also suggest adding more illustrations and screenshots, where relevant and useful, to better explain what users can do with the data management tool.
